services:
  webstatenotifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: webstatenotifier:latest
    container_name: webstatenotifier
    restart: unless-stopped
    env_file:
      - .env
